### ISSUE TITLE
Is there a way to catch the hidden field change from another controller

### ISSUE THREAD

**Issue by salex** [afcapel/stimulus-autocomplete#10]
I'm kinda new to Stimulus but I've managed to change some of my jQuery stuff over.

This is very similar to what I was using in jQuery. My problem is after the hidden field is populated with whatever was selected in the ul targets, how can I catch that change?

One of my uses was to duplicate a bank transaction based on description. You do the autocomplete search and once  a transaction is selected, I'd turn on a button (show) to duplicate the transaction.

I can put a button next to the input field, but it's of no use unless the hidden field is populated. Guess I can fire off an alert saying nothing selected, but that does not feel right.

I tried with another controller to look for the ul to be clicked or the hidden field to be changed and I get no joy. Below is my html/slim f

```
h5 Other Players (or use Search field)
div[data-controller="autocomplete" data-autocomplete-url="/players/search"]
  input[type="text" data-target="autocomplete.input" placeholder="Player Search"]
  input[type="hidden" name="player_id" data-target="autocomplete.hidden callerActions.hidden" data-action="callerActions#showSearched"]
  .w3-right.my-btn.w3-blue[data-action="click->callerActions#addSearched" data-playerid=""] Add Searched
  ul.w3-ul.w3-border[data-target="autocomplete.results"]
```
As a side note, this package is almost 2 year old and I see little action on the Stimulus Discourse - how accepted is Stimulus? I'm becoming comfortable with it but is it going to be around for a while?

**Comment by salex** [comment]
Forgot to say, Good work!

**Comment by salex** [comment]
I got what I needed (a trigger) by adding `data-action="callerActions#showSearched"` to the autocomplete.input target. Guess a hidden field does not respond to change since there is not a text-area, just a value.

I initially thought autocomplete.input would not be a good choice because it would change on every keystroke. It doesn't, so I have a solution.

Thanks

**Comment by afcapel** [comment]
@salex the autocomplete controller emits an `autocomplete.change` event when a new value is selected. You can listen to that event, it has a `detail` property with the selected `value` and `textValue` (label).


```html
<p id="preview"></p>

<div data-controller="autocomplete" data-autocomplete-url="/results.html">
      <input type="text" class="form-control" data-target="autocomplete.input" placeholder="search a bird"/>
      <input type="hidden" name="bird_id" data-target="autocomplete.hidden"/>
      <ul data-target="autocomplete.results" class="list-group"></ul>
 </div>

<script>
document.addEventListener('autocomplete.change', function(e) {
  const { value, textValue } = e.detail

  document.getElementById('preview').innerText = `New value: ${value}. Text: ${textValue}`
})
</script>
```

**Comment by salex** [comment]
I sorry I didn't reply earlier, but thank you for you!

Again I kind of solved my problem in that if the `input` changed, I put up a button to do another action and the hidden target was there for me to get the value (id of some resource).

I moved on to another application and just put up a simple name search. A list of Players (golf group) who use nickname etc and sometimes you have problems finding them in a list. I just did a search on first, last or nickname starting with the search string and initially just  wanted to put up the show page.  Seemed simple, just add a controller(I use slim) to the HTML

```rails
  div[data-controller="autocomplete playerSearch" 
      data-autocomplete-url="/players/player_search" data-autocomplete-min-length="2"]
    input[type="text" data-target="autocomplete.input" placeholder="Player Name Search" 
      data-action="change->playerSearch#showSearched"]
    input[type="hidden" name="player_id" data-target="autocomplete.hidden playerSearch.hidden"  ]
    ul.w3-ul.w3-border[data-target="autocomplete.results" ]
```

Going one step at a time, I just used a location.assign(url) to bring up the show page for the player

```javascript
import { Controller } from "stimulus"

export default class extends Controller {
  static targets = ['hidden' ]

  showSearched(){
    const goto = this.hiddenTarget
    const url = `/players/${goto.value}`
    location.assign(url)
  }
}
```

Didn't work:-(  I did notice that if I displayed the event in the console, the hidden field would not have a value. If I opened up the `input` triangle it would have a value!

I wrapped the code in a timer:

```javascript
   showSearched(){
    const goto = this.hiddenTarget    
    setTimeout(function () {
      const url = `/players/${goto.value}`
      console.log(url)
      // location.assign(url)
    }, 500); 
  }
```

And it worked. Must be that sync/asyc stuff that at 76 I've learned enough!

I tried my best to find event `detail` and could not find the value I entered in the `li's`.  If you can give me what triangle in the console I should open to find it, that would be nice. `event.target.details` is undefined. The timer works, but does not seem right.

I'll add another thing. The jQuery autocomplete I used open up the list of matches in a dropdown that I guess  had a z-index. I tried adding z-index on elements and did not work - never had much luck with z-index. That would be a nice addition.

Again thank you,

**Comment by salex** [comment]
Sometimes you have to ask a question to force you to read through a previous answer.

Not literate in javascript and was confused on the `detail`. I figured it would be in the stimulus 'event.target`, guess not.

Anyhow I still did it will stimulus (just a controller), but nothing more than you pointed out a few weeks ago.

```ruby
div[data-controller="autocomplete playerSearch" 
    data-autocomplete-url="/players/player_search" data-autocomplete-min-length="2"]
  input[type="text" data-target="autocomplete.input" placeholder="Player Name Search" ]
  input[type="hidden" name="player_id" data-target="autocomplete.hidden"  ]
  ul[data-target="autocomplete.results" style="z-index:99;"]
```
Controller - just a connect()

```javascript
import { Controller } from "stimulus"

export default class extends Controller {
  connect(){
    document.addEventListener('autocomplete.change', function(e) {
      const { value, textValue } = e.detail
      location.assign(`/players/${value}`)
    })
  }
}
```

Still give the z-index some though. Guess I could do it in a popup to prevent the whole page from moving down
