### ISSUE TITLE
Feature request : delay option

### ISSUE THREAD

**Issue by apsylone** [afcapel/stimulus-autocomplete#101]
Hi,

It would be a great addition IMHO if we could have a delay option.
For example : 
http://easyautocomplete.com/guide#sec-delay

Really useful when the ajax call asked for a lot of ressources to be executed on backend.

**Comment by afcapel** [comment]
@apsylone there's already a delay. The autocomplete [waits until you stop typing for 300ms](https://github.com/afcapel/stimulus-autocomplete/blob/96318978a42cc9ba35ad88a76cb59d96465f7e3c/src/autocomplete.js#L24) before sending an request to the server. 300ms is a quite typical value for this kind of delay. Although it's not configurable. But we can make it configurable if there's a case for it.

**Comment by afcapel** [comment]
PR to make delay configurable https://github.com/afcapel/stimulus-autocomplete/pull/102

**Comment by apsylone** [comment]
Nice addition. That's exactly what I was looking for :) 
Thanks @afcapel .
