### ISSUE TITLE
Failed to resolve module specifier "stimulus-autocomplete"

### ISSUE THREAD

**Issue by GuillaumeOcculy** [afcapel/stimulus-autocomplete#106]
`Ruby 3.0.3`
`Rails 7.0.0.alpha2`

Hello

After following the instructions to [install][1] and [usage][2], I launch the server and I received this error: `Uncaught TypeError: Failed to resolve module specifier "stimulus-autocomplete". Relative references must start with either "/", "./", or "../".`

```
# app/javascript/controllers/application.js
import { Application } from "@hotwired/stimulus"
import { Autocomplete } from "stimulus-autocomplete"
# and tried import { Autocomplete } from 'stimulus-autocomplete/src/autocomplete'

const application = Application.start()
application.register('autocomplete', Autocomplete)

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```

  [1]: https://github.com/afcapel/stimulus-autocomplete#installation
  [2]: https://github.com/afcapel/stimulus-autocomplete#usage

**Comment by pprencel** [comment]
@GuillaumeOcculy 
Did you add package via `importmap` command?
I had same isssue and I solved it by changing package path in `config/importmap.rb`
```
# pin "stimulus-autocomplete", to: "https://ga.jspm.io/npm:stimulus-autocomplete@3.0.2/src/autocomplete.js"
pin "stimulus-autocomplete", to: "https://cdn.jsdelivr.net/npm/stimulus-autocomplete@3.0.2/src/autocomplete.min.js" 
```

**Comment by afcapel** [comment]
That's correct, I've updated the documentation in 747236e5e10622263196ebee10f035528ce54481.

**Comment by GuillaumeOcculy** [comment]
Thanks @pprencel
