### ISSUE TITLE
Prefilled form

### ISSUE THREAD

**Issue by zairigimad** [afcapel/stimulus-autocomplete#107]
I’m trying to use the autocomplete to get list of items lproducts to prefill a form. For example i serach for product 1. I want to get his id name price to prefill the form.

is there a way to achieve this with the component ?

**Comment by afcapel** [comment]
Not sure I understand exactly what you're trying to achieve but the autocomplete itself won't fill in other fields in a form. You can listen to `autocomplete.change` events and when the autocomplete changes use the new value to fetch other values and fill the form with them, but that's something you'll have to code yourself.
