### ISSUE TITLE
Make the query paramater name `q` customizable

### ISSUE THREAD

**Issue by kulbirsaini** [afcapel/stimulus-autocomplete#111]
It'd be nice if the query paramater name `q` was customizable via the stimulus paramater/value HTML attribute like

```html
<div data-controller="autocomplete"
    data-autocomplete-url-value="/birds/search"
    data-autocomplete-query-param="name_or_desc_cont"
    .... />
```

This will make it really easy to integrate with Rails search gems like [Ransack](https://github.com/activerecord-hackery/ransack).

**Comment by kulbirsaini** [comment]
bump!

**Comment by afcapel** [comment]
Fixed in https://github.com/afcapel/stimulus-autocomplete/pull/112
