### ISSUE TITLE
error event doesn't fire on 400+ response

### ISSUE THREAD

**Issue by benjamin-aubry** [afcapel/stimulus-autocomplete#113]
Hello and thank you for your work,

Can you tell me when the "error" event is supposed to fire ?

For me, a 400 or 500 http response doesn't fire the error event. Maybe it is due to the use of fetch...

Thx

**Comment by afcapel** [comment]
Yes, it follows the `fetch` convention where it only rejects the promise if there's a network error, but not if the server responds with an error. Agree this is not ideal, we can change it to raise on 400-500.
