### ISSUE TITLE
Prevent Lighthouse Aria warnings

### ISSUE THREAD

**Issue by klemens-u** [afcapel/stimulus-autocomplete#117]
A widget with stimulus-autocomplete triggers a warning in Google Chrome devtools "Lighthouse" accessibility section:

```
[aria-*] attributes do not match their roles
Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes. 
```

Solution: add `role="combobox" to the parent element. Example:

```
<div  data-controller="autocomplete"
         data-autocomplete-url-value="/foo"
         role="combobox"
    >
    ...
</div>
```
Please check if this should be added to the code or to the documentation. Thank you!

**Comment by afcapel** [comment]
Thanks for the suggestion, fixed in https://github.com/afcapel/stimulus-autocomplete/pull/118.
