### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by robinaugh** [afcapel/stimulus-autocomplete#129]
Hi @afcapel, thanks for saving us a bunch of time with this controller!

A couple folks have noticed (see https://github.com/afcapel/stimulus-autocomplete/issues/128) that a lot of the functionality documented in the readme is not actually supported by the version of `stimulus-autocomplete` currently available via `yarn`, because there's been a lot of work done since the last release (a year ago today).

I've got it pinned to the current `main` branch's SHA in my team's project as a workaround, but it'd be great if we could get a new release sometime. Thanks again!

**Comment by afcapel** [comment]
Sure, I’m on vacation at the moment, but I can cut a new release next week.

**Comment by ACPK** [comment]
Great catch!

**Comment by afcapel** [comment]
I've just released [v3.1.0](https://github.com/afcapel/stimulus-autocomplete/releases/tag/v3.1.0). Enjoy!
