### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by miketheman** [afcapel/stimulus-autocomplete#2]
Hi there! I'm trying to use your library, and am having trouble adapting it to a Rails stack (without bootstrap).

The example page refers to a file that isn't found in the repo:
https://github.com/afcapel/stimulus-autocomplete/blob/0e37a3ff404a3a28228b204cd25958be71334871/examples/index.html#L16

which results in a 404.

Is there another example I can refer to? Looking forward to using this more!

**Comment by afcapel** [comment]
Hi @miketheman I've [updated the example](https://github.com/afcapel/stimulus-autocomplete/commit/6add77eefacef0f7752d63ec86695350a57a093d) to use a minimal webpack config and [added some documentation on how to run it](https://github.com/afcapel/stimulus-autocomplete#examples).

Hope that helps, but let me know if run into any issues.

**Comment by miketheman** [comment]
Thanks, I'll give it a try!
