### ISSUE TITLE
suggestion: center selected item (scroll)

### ISSUE THREAD

**Issue by drnic** [afcapel/stimulus-autocomplete#25]
Currently, if there are more autocomplete menu items than fit in the visible area, the "down" key even will happily move to items that are not visible. Perhaps we could scroll the menu so that selected items are always visible?

![demo](https://p198.p4.n0.cdn.getcloudapp.com/items/2Nu0d4Bz/Screen%20Recording%202020-11-19%20at%2007.56.35%20am.gif?v=9a1e1100dacd5a18d7e908a96cb1a284)

**Comment by Ahmed-Salem-Baqtyan** [comment]
@afcapel 


Any updates about the above issue, I think it will be better if we do a scrolled drop-down list.

**Comment by afcapel** [comment]
This works as expected in v3.0.0-rc.6.

Demo at https://deploy-preview-91--stimulus-autocomplete.netlify.app/long.html
