### ISSUE TITLE
Document how to cut npm releases

### ISSUE THREAD

**Issue by drnic** [afcapel/stimulus-autocomplete#36]
@afcapel if you can recall, could you document how you would build + cut an npm release?

I know I had some issues #22 with some of the commands last year when I gave them a try; so perhaps I was doing something wrong/using some unused commands.

**Comment by afcapel** [comment]
@drnic here you go https://github.com/afcapel/stimulus-autocomplete#release-a-new-version

Let me know if you have any questions.

**Comment by drnic** [comment]
@afcapel thanks mate; it looks good on my end. If you'd like me to take over/help cutting releases (e.g. v1.4.2 + v.1.5.0), please add npm user `drnic` so I can `npm publish`.
