### ISSUE TITLE
example app - Can't resolve 'stimulus'

### ISSUE THREAD

**Issue by drnic** [afcapel/stimulus-autocomplete#40]
@afcapel I thought I'd add some bonus examples; but I'm struggling to get the example app running -- and perhaps there's a gap in my nodejs setup or something you do to get the example app running?

```
yarn run build # fails with or without dist/ folder
cd examples
rm -rf node_modules # just to make sure
yarn
npm run start
```

And amongst the output is the following error:

```
> stimulus-autocomplete-example@1.2.1 start /Users/drnic/workspace/stimulus-autocomplete/examples
> webpack-dev-server --config webpack.dev.js --mode development
...

ERROR in ../src/autocomplete.mjs
Module not found: Error: Can't resolve 'stimulus' in '/Users/drnic/workspace/stimulus-autocomplete/src'
 @ ../src/autocomplete.mjs 31:0-38 338:2-12
 @ ./app.js
```

Any protips or things you can think of for what might be missing from my environment?

```
$ node -v
v14.15.3
$ npm -v
6.14.9
```

**Comment by afcapel** [comment]
@drnic I've moved the example app to its own repository at https://github.com/afcapel/stimulus-autocomplete-example

Let me know if there's any problems with that repo.

Bundling the example with the library and changing its webpack config to use the source in the parent directory could be more convenient for development, but after trying for a while I couldn't make it work reliably.
