### ISSUE TITLE
Feature Request: partial string highlight

### ISSUE THREAD

**Issue by jmarsh24** [afcapel/stimulus-autocomplete#42]
A useful feature for this library would be to highlight the characters in the autocomplete that match the search string. Similar to how they do it on YouTube.

![Screen Shot 2021-01-09 at 5 36 25 PM](https://user-images.githubusercontent.com/48605824/104103232-4a9dcd00-52a1-11eb-8e7f-4bda71793ae9.png)

**Comment by drnic** [comment]
Suggestion: implement this in the `search.html.erb` partial/action that you return to the autocomplete controller -- you then control exactly which and how you'd like your characters to be highlighted.

**Comment by drnic** [comment]
I'll close this ticket for now.
