### ISSUE TITLE
Feature Request: Down arrow navigation through results

### ISSUE THREAD

**Issue by jmarsh24** [afcapel/stimulus-autocomplete#43]
One feature that GitHub autocomplete has is the ability to navigate through the search results by pressing down and up arrow.  This would be really great to have in this stimulus add on!

**Comment by drnic** [comment]
Up/Down arrow is coded now https://github.com/afcapel/stimulus-autocomplete/blob/master/src/autocomplete.mjs#L80-L93

If you've tried it and its not working, let's see if we can figure out what's broken. I'll close this ticket for now.

**Comment by jmarsh24** [comment]
I have it integrated in my app on tangotube.tv. 
`    <div class="search_bar">
      <%= form_with(url: root_path, method: :get, local: true) do |form| %>
        <%= content_tag :div, 'data-controller': "autocomplete", "data-autocomplete-url": search_suggestions_path do %>
          <%= text_field_tag :query, @current_search, 'data-autocomplete-target': 'input', class: "input" %>
          <%= tag :ul, 'data-autocomplete-target': 'results', class: 'autocomplete' %>
        <% end %>
          <%= form.button fa_icon("search"), class: "button_search", name: nil %>
      <% end %>
    </div>`
    
    This is the ruby code behind it and it was inspired by the DriftingRuby episode on how to implement your add-on.
