### ISSUE TITLE
[RFC] Support for useTransition with consistent "toggle" event (or new open/close events)

### ISSUE THREAD

**Issue by weaverryan** [afcapel/stimulus-autocomplete#59]
Hi!

FYI - I would be fully open to submitting a PR for this feature :).

I'd like to integrate the useTransition() mixin from stimulus-use - https://stimulus-use.github.io/stimulus-use/#/use-transition - to get a nice fade in/fade out effect. To do that, I need an event from `stimulus-autocomplete` that allows me to know when the results target is being shown/hidden.

`stimulus-autocomplete` *does* have a `toggle` event, but it's only used in the `open()` and `close()` methods: no `toggle` event is triggered as a result of the AJAX call or if the results close due to a "blur" in the input.

I believe we can support this fairly easily:

1. Dispatch a new `open` event in ALL cases when the results target *changes* from "closed" to "opened"
2. Similarly, dispatch a `close` event in ALL cases when the results target *changes* from "opened" to "closed"
3. A new option/value - `useHiddenAttribute` - that defaults to `true`. If this is set to `false`, then the library will not add/remove the `this.element.hidden`. This will allow users to apply their own logic.

With this setup (and I would verify this) I believe you could use the built-in controller from `stimulus-autocomplete` and the built-in `transition` controller from `stimulus-use` entirely in HTML to add fading out to this library, without custom JavaScript.

Any issues with this proposal?

Cheers and thanks for the wonderful library!

**Comment by drnic** [comment]
I am happy to see more events emitted.

We can discuss their names once you propose a PR?

**Comment by weaverryan** [comment]
It took me a bit longer than I expected to find time, but I have a proposal now up on #61

Thanks!
