### ISSUE TITLE
Should the query param be configurable?

### ISSUE THREAD

**Issue by miketheman** [afcapel/stimulus-autocomplete#6]
I was implementing this on my app, and noticed that the query string param is `?q=<text>` - and found:
https://github.com/afcapel/stimulus-autocomplete/blob/a1665e7bed6d822abaf7c04980a77e6290284bca/src/autocomplete.mjs#L176

Is this a standard parameter convention, or should this be user-configurable? I was using `?query=<text>` in my app before.

**Comment by afcapel** [comment]
Adding an attribute to configure the query param should be easy, but I'm curious why do you need this. The library already assumes that you have control over the server side endpoint, as you have to render some very specific html.

**Comment by miketheman** [comment]
I probably don't actually need this after all. I think part of it was that I was trying to use this library as a drop in replacement and not modify anything on the backend, so configuring this to support my current query string parameter would have made it a simpler evaluation. 
I was also looking for any url querystring "standards" and didn't find any, so I am happy to close this out with a "let's not add complexity unless it's needed".
