### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by JoeMcNuggets** [afcapel/stimulus-autocomplete#60]
Hello!

There is no license in the repo, so this library should be treated as a proprietary code. Could you specify the license in repository, please?

**Comment by drnic** [comment]
@afcapel ok for me to add an MIT license under your name?

**Comment by drnic** [comment]
@JoeMcNuggets note: package.json mentions "license: MIT"

**Comment by afcapel** [comment]
Fixed in 019b7ded70b0e3f99ffaf686d508a5b76dc28356
