### ISSUE TITLE
Request for additional maintainer

### ISSUE THREAD

**Issue by drnic** [afcapel/stimulus-autocomplete#75]
I'm excited for the activity in this project. I'm not currently using autocomplete in my latest projects nor am I ready to upgrade to stimulus 3 just yet.

Is there someone who would like to merge branches, cut releases, and perhaps as a bonus can maintain releases for Stimulus v2 + Stimulus v3 for a while until the community has long migrated to Stimulus 3?

**Comment by salex** [comment]
Thanks for acknowledging that you are the current stuckie! I wish I could help but I know nothing about merging branches or how stuff is pushed. Let alone that Javascript is not something I'm proficient in.

Hope someone steps up.

**Comment by afcapel** [comment]
@drnic thank you very much for your help all this time ❤️

I'm happy to maintain the project and cut new releases, but if someone else wants to participate I'll be happy to add new maintainers and assist them as well.
