### ISSUE TITLE
Release Tags on GitHub?

### ISSUE THREAD

**Issue by weaverryan** [afcapel/stimulus-autocomplete#85]
Hi!

I noticed that new releases are being published to npm, but not on GitHub. That is, of course, totally possible and allowed :). But it's a little less traditional, and I got confused at first when checking for new releases (as I check GitHub first). Would you be willing to publish tags to GitHub as well? It's minor - but would be appreciated.

Cheers!

**Comment by afcapel** [comment]
@weaverryan thanks for the heads up. 

I've added the missing releases and a script to automatically tag new ones.
