### ISSUE TITLE
Additional attribute

### ISSUE THREAD

**Issue by pruzicka** [afcapel/stimulus-autocomplete#86]
Hi, 
would it be somehow possible to gather additional attribute from autocompleted model? Now with 
`<input type="hidden" name="bird_id" data-autocomplete-target="hidden"/>` I could add `bird_id` to the form. I could use another attribute that would be pulled from Birds model, let's say I would have "color: 'blue'" or "night_bird:true" in the model. I  would use it in the form to style/disable another fields.
Thank you

Petr R.

**Comment by afcapel** [comment]
@pruzicka I've added the selected element to the `autocomplete.change` event in #87. Now you can easily pull any extra details from the selected option in that event. See that PR for details and an example.

**Comment by pruzicka** [comment]
Pure awesomness @afcapel  Thank you.

**Comment by pruzicka** [comment]
Works like a charm. Thank you @afcapel
