### ISSUE TITLE
Module parse failed: Unexpected token error

### ISSUE THREAD

**Issue by extendednotes** [afcapel/stimulus-autocomplete#90]
Unfortunately I do get the following error message from webpacker with the latest rc5 version:

> Uncaught Error: Module parse failed: Unexpected token (7:17)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
> | 
> | export default class Autocomplete extends Controller {
> >   static targets = ["input", "hidden", "results"]
> |   static classes = ["selected"]
> |   static values = {

Does anyone know how to solve this? Thx in advance!

**Comment by afcapel** [comment]
@extendednotes what version of webpacker are you using?
[
This example rails app](https://github.com/afcapel/stimulus-autocomplete-rails-example) works fine with rc5 and webpacker v5 with default settings.

**Comment by extendednotes** [comment]
Hey @afcapel, thanks for your great work and your quick reply. I'm on the latest rails/webpacker version (5.4.3) which still depens  on webpack@4.46.0.

**Comment by afcapel** [comment]
The example app also [uses webpack@4.46.0](https://github.com/afcapel/stimulus-autocomplete-rails-example/blob/f49bea40420fdb9edd4a1e50becbb940e3eda27d/package.json#L6).

There must some difference in the webpacker config. Maybe compare both [webpacker.yml files](https://github.com/afcapel/stimulus-autocomplete-rails-example/blob/f49bea40420fdb9edd4a1e50becbb940e3eda27d/config/webpacker.yml) and see if you spot anything.

**Comment by extendednotes** [comment]
Okay, I'm sorry that was my fault. I just found out, that I probably excluded node_modulues from babel-loader manually a long time ago with "environment.loaders.delete('nodeModules')" in environment.js Thanks again for pointing me in the right direction.

**Comment by afcapel** [comment]
No worries, glad it's working now.
